meta_product_name: "Ji Dok Che"
meta_title: "Ji Dok Che - Yoga"
meta_description: "Natha Yoga im Raum Zürich - Gruppen-, Einzel- und Privatlektionen"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards